name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    # To enable auto publishing to github, update your electron publisher
    # config in package.json > "build" and remove the conditional below

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]
    permissions:
      contents: write
      discussions: write
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Configure Git user
        run: |
          git config --global user.email "suyashpandey152@gmail.com"
          git config --global user.name "usersuyashpandey"

      - name: Navigate to release/app directory
        run: cd release/app

      - name: Increment Patch Version in release/app/package.json
        run: |
          npm version patch

      - name: Extract version
        id: version
        run: |
          NEW_VERSION=$(node -p 'require("./release/app/package.json").version')
          echo "New version $NEW_VERSION detected"
          echo "::set-output name=version::$NEW_VERSION"

      - name: Create a git tag
        if: env.NEW_VERSION
        run: |
          git tag v${NEW_VERSION}
          git push --tags
        env:
          NEW_VERSION: ${{ env.NEW_VERSION }}

      - name: Merge version bump commit
        run: |
          git fetch origin main
          git checkout main
          git merge --ff-only HEAD@{1}

      - name: Push merged changes
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Pull latest changes
        run: git pull origin main

      - name: Navigate back to root directory
        run: cd ../..

      - name: Git pull
        run: git pull

      - name: Install and build
        run: |
          npm install --force
          npm run postinstall
          npm run build

      - name: Publish releases
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm exec electron-builder -- --publish always --win --mac
