name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Pull latest changes
        run: git pull origin main

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install and build
        run: |
          npm install --force
          npm run postinstall
          npm run build

      - name: Publish releases
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          VERSION: ${{ needs.configure-git.outputs.version }}
        run: |
          npm exec electron-builder -- --publish always --win --mac --linux"
