name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    # To enable auto publishing to github, update your electron publisher
    # config in package.json > "build" and remove the conditional below

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Navigate to release/app directory
        run: cd release/app

      - name: Increment Patch Version in release/app/package.json
        run: npm version patch --force

      - name: Commit Version Changes
        run: |
          git config --local user.email "suyashpandey152@gmail.com"
          git config --local user.name "usersuyashpandey"
          git add .
          git commit -m "Incremented patch version"
          git push

      - name: Navigate back to root directory
        run: cd ../..

      - name: Git pull
        run: git pull

      - name: Install and build
        run: |
          npm install --force
          npm run postinstall
          npm run build

      - name: Publish releases
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm exec electron-builder -- --publish always --win --mac
